### ISSUE TITLE
map head to revision

### ISSUE THREAD

**Issue by OEP** [ScottDuckworth/python-anyvcs#2]
Seems like there needs to be a way to map heads to revisions. This sort of grows out of necessity since SVN doesn't support things like 'HEAD' and 'trunk' as the 'rev' argument for the various queries. How to interpret that seems like another can of worms.

What do you think? I ran into this problem on buffet since (ideally) I shouldn't have to check if the repo I'm looking at is git/hg/svn.

**Comment by ScottDuckworth** [comment]
I've had some ideas tumbling around in my head on this topic.  Since Subversion doesn't have true branches and tags it makes it a bit tricky, but I think it's possible to fake it.

It would be ideal to be able to pass any head, as returned by SvnRepo.heads(), to the rev parameter of any method, and those methods internally prepend the necessary stuff to the path.  Also, having the ability to specify a specific revision on a head might be nice.

Here are some examples, assuming svnrepo is an instance of SvnRepo and svnrepo.heads() returns ['HEAD', 'trunk', 'branches/a']:

svnrepo.ls('HEAD', '/x') - maps to /x on the youngest revision
svnrepo.ls('trunk', '/x') - maps to /trunk/x on the youngest revision
svnrepo.ls('branches/a', '/x') - maps to /branches/a/x on the youngest revision
svnrepo.ls('HEAD:5', '/x') - maps to /x on revision 5, same as svnrepo.ls(5, '/x')
svnrepo.ls('trunk:5', '/x') - maps to /trunk/x on revision 5
svnrepo.ls('branches/a:5', '/x') - maps to /branches/a/x on revision 5

**Comment by ScottDuckworth** [comment]
Implemented in 05402264831e81d183940373df399463490fc475
